import { BaseModel } from "./baseModel";
import { Client } from "./client";
import { DocumentItem } from "./documentItem";

export interface Document extends BaseModel {
    additional_information: null;
    applied: number;
    caja_id: null;
    cdr: any;
    client_business_unit_id: number;
    client_id: number;
    correlative: number;
    credit_days: any;
    currency_type_id: string;
    detraction_account: string;
    detraction_pay_constancy: string;
    detraction_percent: string;
    detraction_type_id: string;
    discounts: string;
    document_type_id: string;
    establishment_id: number;
    establishment: null;
    exchange_rate_sale: string;
    expiration_date: string;
    external_id: string;
    fees_number: number;
    filename: null;
    group_id: string;
    has_cdr: number;
    has_pdf: number;
    has_xml: number;
    hash: null;
    igv: string;
    is_anulate_simple: number;
    is_detraction: number;
    is_fees: number;
    is_perception: number;
    is_retention: number;
    issue_date: string | null;
    legends: null;
    low_reason: string;
    operation_type_id: string;
    pay_constancy_detraction: string;
    payment_method_type_id: string;
    pdf: any;
    perception_percent: string;
    purchase_order: string;
    qr: null;
    registration_date: string;
    restore_user_id: null;
    retention_percent: string;
    serie: string;
    soap_type_id: string;
    state_type_id: string;
    status_paid: number;
    sunat_information: null;
    total_aplicado_nc: number;
    total_applied_nc: number;
    total_base_isc: number;
    total_detraction: number;
    total_discount: number;
    total_exonerated: number;
    total_free: number;
    total_isc: number;
    total_paid: number;
    total_pending: number;
    total_perception: number;
    total_retention: number;
    total_taxes: number;
    total_unaffected: number;
    total_value: number;
    total: number;
    ubl_version: string;
    warehouse_id: number;    
    xml: any;

    client?: Client;
    document_items: DocumentItem[];
}